name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake ninja-build libasound2-dev libopencv-dev stockfish
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          wget -qO- https://github.com/microsoft/onnxruntime/releases/download/v1.17.1/onnxruntime-linux-x64-1.17.1.tgz | tar xvz -C ~/
          sudo mkdir -p /usr/local/include/onnxruntime
          sudo mv ~/onnxruntime-linux-x64-1.17.1/include/* /usr/local/include/onnxruntime
          sudo mv ~/onnxruntime-linux-x64-1.17.1/lib/* /usr/local/lib
      - name: Build
        run: |
          CXX=/usr/bin/clang++-18 ./build.sh
