name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ cmake ninja-build libasound2-dev libopencv-dev
      - name: Build
        run: |
          cmake -B build -G Ninja
          cmake --build build
          bash build/_deps/whisper.cpp-src/models/download-ggml-model.sh small.en
