name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ cmake ninja-build libasound2-dev libopencv-dev
          wget -qO- https://github.com/microsoft/onnxruntime/releases/download/v1.17.0/onnxruntime-linux-x64-1.17.0.tgz | tar xvz -C ~/
          sudo mkdir -p /usr/local/include/onnxruntime
          sudo mv ~/onnxruntime-linux-x64-1.17.0/include/* /usr/local/include/onnxruntime
          sudo mv ~/onnxruntime-linux-x64-1.17.0/lib/* /usr/local/lib
      - name: Build
        run: |
          ./build.sh
